apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tapcbdemo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: component-a
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/0pens0/spring-http
      ref:
        branch: main