apiVersion: v1
kind: Secret
metadata:
  name: carbonblack-config-secret
  namespace: my-apps
stringData:
  cbc_api_id: 
  cbc_api_key: 
  cbc_org_key: 
  cbc_saas_url: https://defense-test03.cbdtest.io/containers
