apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ImageScan
metadata:
  name: sample-carbonblack-public-image-scan
  namespace: my-apps
  labels:
    'app.kubernetes.io/part-of': 'component-a'
spec:
  registry:
    image: "nginx:1.16"
  scanTemplate: carbonblack-public-image-scan-template
  scanPolicy: carbonblack-scan-policy
